export const SOP_OPTIONS = [
  {
    module: '1',
    label: 'Module 1 – Food Safety Management System (FSMS)',
    options: [
      { value: '1.01', label: '1.01 - Management System' },
      { value: '1.02', label: '1.02 - Control of Documents and Records' },
      { value: '1.03', label: '1.03 - Procedures and Corrective Actions' },
      { value: '1.04', label: '1.04 - Internal and External Inspections' },
      { value: '1.05', label: '1.05 - Release of Items/Product' },
      {
        value: '1.06',
        label: '1.06 - Supplier/Service Provider Monitoring & Control',
      },
      { value: '1.07', label: '1.07 - Traceability and Recall' },
      { value: '1.08', label: '1.08 - Intentional Contamination' },
    ],
  },
  {
    module: '2',
    label: 'Module 2 – Farm - Good Agricultural Practices',
    options: [
      { value: '2.01', label: '2.01 - General' },
      { value: '2.02', label: '2.02 - Site' },
      { value: '2.03', label: '2.03 - Ground History' },
      { value: '2.04', label: '2.04 - Adjacent Land Use' },
      { value: '2.05', label: '2.05 - Inspection' },
      { value: '2.06', label: '2.06 - Training' },
      { value: '2.07', label: '2.07 - Field Worker Hygiene' },
      { value: '2.08', label: '2.08 - Agricultural Water' },
      { value: '2.09', label: '2.09 - Soil Amendments' },
      { value: '2.10', label: '2.10 - Equipment and Harvest Crew' },
      { value: '2.11', label: '2.11 - Harvest Practices' },
    ],
  },
  {
    module: '3',
    label: 'Module 3 – Indoor Agriculture',
    options: [
      { value: '3.01', label: '3.01 - General' },
      { value: '3.02', label: '3.02 - Site' },
      { value: '3.03', label: '3.03 - Pest Control' },
      { value: '3.04', label: '3.04 - General Chemicals' },
      { value: '3.05', label: '3.05 - Maintenance and Sanitation' },
      { value: '3.06', label: '3.06 - Operational Practices' },
      { value: '3.07', label: '3.07 - Receiving and Shipping' },
      { value: '3.08', label: '3.08 - Training' },
      { value: '3.09', label: '3.09 - Worker Hygiene' },
      { value: '3.10', label: '3.10 - Agronomic Inputs' },
      { value: '3.11', label: '3.11 - Water Use' },
      { value: '3.12', label: '3.12 - Pesticide Usage' },
      { value: '3.13', label: '3.13 - Pesticide Handling' },
      { value: '3.14', label: '3.14 - Testing (CEA)' },
    ],
  },
  {
    module: '4',
    label: 'Module 4 – Harvest Crew',
    options: [
      { value: '4.01', label: '4.01 - General' },
      { value: '4.02', label: '4.02 - Inspection' },
      { value: '4.03', label: '4.03 - Training' },
      { value: '4.04', label: '4.04 - Harvest Worker Hygiene' },
      { value: '4.05', label: '4.05 - Harvest Practices' },
      { value: '4.06', label: '4.06 - Sanitation' },
      { value: '4.07', label: '4.07 - Equipment and Tools' },
      { value: '4.08', label: '4.08 - Production Water' },
    ],
  },
  {
    module: '5',
    label: 'Module 5 – Facility',
    options: [
      { value: '5.01', label: '5.01 - General' },
      { value: '5.02', label: '5.02 - Pest Control' },
      { value: '5.03', label: '5.03 - Storage Areas' },
      { value: '5.04', label: '5.04 - Operational Practices' },
      { value: '5.05', label: '5.05 - Worker Practices' },
      { value: '5.06', label: '5.06 - Equipment' },
      { value: '5.07', label: '5.07 - Equipment Cleaning' },
      { value: '5.08', label: '5.08 - General Cleaning' },
      { value: '5.09', label: '5.09 - Facility Maintenance' },
      { value: '5.10', label: '5.10 - Water Supply' },
      { value: '5.11', label: '5.11 - Ice' },
      { value: '5.12', label: '5.12 - Glass and Brittle Plastics' },
      { value: '5.13', label: '5.13 - Waste Disposal' },
      { value: '5.14', label: '5.14 - Worker Facilities' },
      { value: '5.15', label: '5.15 - Receiving and Storage' },
      { value: '5.16', label: '5.16 - Shipping' },
      { value: '5.17', label: '5.17 - Transportation' },
      { value: '5.18', label: '5.18 - Traceability and Labeling' },
    ],
  },
  {
    module: '6',
    label: 'Module 6 – HACCP',
    options: [
      { value: '6.01', label: '6.01 - HACCP General' },
      { value: '6.02', label: '6.02 - Hazard Analysis and CCP' },
      { value: '6.03', label: '6.03 - HACCP Execution' },
    ],
  },
  {
    module: '7',
    label: 'Module 7 – Food Safety Plan (Preventive Controls)',
    options: [
      { value: '7.01', label: '7.01 - FSMA General' },
      {
        value: '7.02',
        label: '7.02 - Hazard Analysis and Preventive Controls',
      },
      { value: '7.03', label: '7.03 - Preventive Controls Execution' },
      { value: '7.04', label: '7.04 - Supply Chain Program' },
    ],
  },
] as const;

export const CATEGORY_OPTIONS = [
  {
    value: 'Sanitation & Hygiene',
    label: 'Sanitation & Hygiene',
  },
  {
    value: 'Maintenance & Calibration',
    label: 'Maintenance & Calibration',
  },
  {
    value: 'Production & Operations',
    label: 'Production & Operations',
  },
  {
    value: 'Shipping & Receiving',
    label: 'Shipping & Receiving',
  },
  {
    value: 'Personnel & Training',
    label: 'Personnel & Training',
  },
  {
    value: 'Suppliers',
    label: 'Suppliers',
  },
  {
    value: 'Others',
    label: 'Others',
  },
] as const;
